config/routes.rb
Rails.application.routes.draw do
  root to: 'reports#index'

  resources :invoices
  resources :purchases
  resources :items
  resources :customers, only: [:index, :show, :edit, :update]

  get '/invoice_details/:id', to: 'invoices#details_json'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :invoice_details, dependent: :destroy
  belongs_to :customer

  validates :customer, presence: true

  def calculate_total!
    self.total = invoice_details.reduce(0) {|sum, detail| sum += detail.total }
    save!
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @items = Item.all
    @invoice = Invoice.new
    @form_option = {}
    @form_option[:url] = invoices_url
    @form_option[:method] = :post
  end

  # GET /invoices/1/edit
  def edit
    @items = Item.all
    @form_option = {}
    @form_option[:url] = invoice_url(@invoice)
    @form_option[:method] = :patch
  end

  # POST /invoices
  # POST /invoices.json
  def create
    ActiveRecord::Base.transaction do
      @invoice = Invoice.new invoice_params
      customer = Customer.find_or_create_by(name: params[:customer_name])
      @invoice.customer = customer
      @invoice.save!

      Item.all.each do |item|
        if params["amount_#{item.id}"].to_i > 0
          InvoiceDetail.create!(invoice: @invoice, item: item, price: item.price,
                                amount: params["amount_#{item.id}"].to_i)
        end
      end
    end

    respond_to do |format|
      if @invoice.calculate_total!
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    ActiveRecord::Base.transaction do
      @invoice.update invoice_params
      @invoice.invoice_details.destroy_all
      Item.all.each do |item|
        if params["amount_#{item.id}"].to_i > 0
          InvoiceDetail.create!(invoice: @invoice, item: item, price: item.price,
                                amount: params["amount_#{item.id}"].to_i)
        end
      end
    end
    @invoice.reload
    respond_to do |format|
      if @invoice.calculate_total!
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def details_json
    @invoice = Invoice.find(params[:id])
    details = @invoice.invoice_details
    details.each { |detail| detail[:item_id] = detail.item.id }

    respond_to do |format|
      format.json { render json: @invoice.invoice_details }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.permit(:deliver_address, :contactor, :contact_phone, :delivered)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<h3>訂單資料</h3>
<%= bootstrap_form_tag url: @form_option[:url], method: @form_option[:method] do |f| %>
  <%= label_tag 'customer_name', "訂購人" %>
  <%= f.text_field "customer_name", { hide_label: true, value: @invoice.customer ? @invoice.customer.name : '' }%>
  <%= label_tag "deliver_address", '寄送地址' %>
  <%= f.text_field "deliver_address", { hide_label: true, value: @invoice.deliver_address } %>
  <%= label_tag "contactor", '聯絡人' %>
  <%= f.text_field "contactor", { hide_label: true, value: @invoice.contactor } %>
  <%= label_tag "contact_phone", '聯絡電話' %>
  <%= f.phone_field "contact_phone", { hide_label: true, value: @invoice.contact_phone } %>
  <%= f.check_box :delivered, value: @invoice.delivered, checked: @invoice.delivered, label: "已送貨？" %>
  <hr>
  <table class="table">
    <thead>
      <tr>
        <th>品項</th>
        <th>單價</th>
        <th>數量</th>
        <th>總價</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr id="<%= item.id %>">
          <td><%= item.name %></td>
          <td><%= item.price %></td>
          <td class="amount"><%= f.number_field "amount_#{item.id}",  hide_label: true %></td>
          <td class="detail_total" id="total_<%= item.id%>">0</td>
        </tr>
      <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td id="total"><b>$ 0</b></td>
        </tr>
    </tbody>
  </table>
  <%= f.submit %>
<% end %>

<script>
  function calculateTotal(){
    $total = 0;
    $.each($(".detail_total"), function(index, value){
      $total += Number($(value).text());
    });
    $("#total").html("<b>$ " + $total + "</b>");
  }

  $( ".amount" ).change(function() {
    $price = Number($(this).prev().text());
    $amount = Number($(this).children().children().last().val());
    $(this).next().html($price * $amount);

    calculateTotal();

    if($amount > 0){
      $(this).parent().css("background-color", "#87CEFA");
    }else{
      $(this).parent().css("background-color", "white");
    }
  });
</script>

app/views/invoices/edit.html.erb
<div class="page-header">
  <%= link_to invoices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @invoice, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>修改訂單</h1>
</div>

<%= render 'form' %>

<script>
  $( document ).ready(function() {
      $.get("/invoice_details/<%= @invoice.id %>.json", function(data, status){
        // alert("Data: " + data + "\nStatus: " + status);
        $.each(data,function(index, value){
          $id = value.item_id;
          if(value.amount > 0){
            $('#amount_' + $id).val(value.amount);
            $('#amount_' + $id).parent().parent().parent().css("background-color", "#87CEFA");
            $('#total_' + $id).text(value.amount * value.price);
            $('#amount_' + $id).parent().parent().prev().text(value.price);
          }
        });

        calculateTotal();
      });

  });
</script>

app/views/invoices/index.html.erb
<div class="page-header">
  <%= link_to new_invoice_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    新訂單
  <% end %>
  <h1>訂單清單</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>訂購人</th>
        <th>總價</th>
        <th>已送貨？</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @invoices) do |invoice| %>
        <td><%= invoice.id %></td>
        <td><%= invoice.customer.name %></td>
        <td>$ <%= invoice.total %></td>
        <td>
          <% if invoice.delivered? %>
            <span class="glyphicon glyphicon-ok green" aria-hidden="true"></span>
          <% else %>
            <span class="glyphicon glyphicon-remove red" aria-hidden="true"></span>
          <% end %>
        </td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/new.html.erb
<div class="page-header">
  <%= link_to invoices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>新訂單</h1>
</div>

<%= render 'form' %>

app/views/invoices/show.html.erb
<div class="page-header">
  <%= link_to invoices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    返回
  <% end %>
  <%= link_to edit_invoice_path(@invoice), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    編輯訂單
  <% end %>
  <h1>訂單資料</h1>
</div>

<dl class="dl-horizontal">
  <dt>訂購人：</dt>
  <dd>$ <%= @invoice.customer.name %></dd>

  <dt>送貨地址</dt>
  <dd><%= @invoice.deliver_address %></dd>

  <dt>聯絡人</dt>
  <dd><%= @invoice.contactor %></dd>

  <dt>聯絡人電話</dt>
  <dd><%= @invoice.contact_phone %></dd>

  <dt>總計:</dt>
  <dd>$ <%= @invoice.total %></dd>

  <dt>已送貨？:</dt>
  <dd>
    <% if @invoice.delivered? %>
      <span class="glyphicon glyphicon-ok green" aria-hidden="true"></span>
    <% else %>
      <span class="glyphicon glyphicon-remove red" aria-hidden="true"></span>
    <% end %>
  </dd>

  <dt>明細</dt>
  <dd>
   <table class="table">
    <thead>
      <tr>
        <th>品項</th>
        <th>單價</th>
        <th>數量</th>
        <th>複價</th>
      </tr>
    </thead>
    <tbody>
    <% @invoice.invoice_details.each do |detail| %>
      <% next if detail.amount == 0 %>
      <tr>
        <td><%= detail.item.name %></td>
        <td><%= detail.price %></td>
        <td><%= detail.amount %></td>
        <td><%= detail.total %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </dd>
</dl>