config/routes.rb
Rails.application.routes.draw do
  root to: 'reports#index'

  resources :invoices
  resources :purchases
  resources :items
  resources :customers, only: [:index, :show, :edit, :update]

  get '/invoice_details/:id', to: 'invoices#details_json'
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :invoices
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update]

  def index
    @customers = Customer.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :phone, :address, :email)
  end
end

app/views/customers/edit.html.erb
<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @customer, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>客戶資料</h1>
</div>

<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :phone %>
    <%= f.input :address %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/index.html.erb
<div class="page-header">
  <h1>客戶名單</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>客戶名稱</th>
        <th>電話</th>
        <th>地址</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @customers) do |customer| %>
        <td><%= customer.id %></td>
        <td><%= customer.name %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.address %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/show.html.erb
<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    返回
  <% end %>
  <%= link_to edit_customer_path(@customer), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    編輯資料
  <% end %>
  <h1>Show customer</h1>
</div>

<dl class="dl-horizontal">
  <dt>客戶名:</dt>
  <dd><%= @customer.name %></dd>

  <dt>電話:</dt>
  <dd><%= @customer.phone %></dd>

  <dt>地址:</dt>
  <dd><%= @customer.address %></dd>

  <dt>Email:</dt>
  <dd><%= @customer.email %></dd>

</dl>