config/routes.rb
Rails.application.routes.draw do
  root to: 'reports#index'

  resources :invoices
  resources :purchases
  resources :items
  resources :customers, only: [:index, :show, :edit, :update]

  get '/invoice_details/:id', to: 'invoices#details_json'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :purchases
  has_many :invoice_details

  validates :name, :price, :amount, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :amount, :price, :eastsun_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :amount %>
    <%= f.input :price %>
    <%= f.input :eastsun_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @item, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing item</h1>
</div>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="page-header">
  <%= link_to new_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    新增商品
  <% end %>
  <%= link_to '進貨清單', purchases_path, class: 'btn btn-primary' %>
  <h1>商品清單</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>東日編號</th>
        <th>商品名</th>
        <th>庫存</th>
        <th>價格</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @items) do |item| %>
            <td><%= item.id %></td>
            <td><%= item.name %></td>
            <td><%= item.amount %></td>
            <td><%= item.price %></td>
            <td><%= link_to '進貨', new_purchase_path + "?item_id=#{item.id}"  %>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New item</h1>
</div>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_item_path(@item), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show item</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @item.name %></dd>

  <dt>Amount:</dt>
  <dd><%= @item.amount %></dd>

  <dt>Price:</dt>
  <dd><%= @item.price %></dd>

  <dt>Eastsun:</dt>
  <dd><%= @item.eastsun_id %></dd>

</dl>